### PR TITLE
Presentation refactoring

### PR DESCRIPTION
**Pull request by roylin2000**
I refactored the render functions from levelManager to levelGameplayController. I didn't notice any other use cases with presenter methods, but there is a good chance that I missed it. Please comment or DM me if you see this violation elsewhere.

### CODE REVIEW

**Review by matrix-marker — CHANGES_REQUESTED** [review]
almost good to go!!

currently, 

```
inputController.handleInputs(dt);
levelManager.step(dt);
```
are invokeed in `LevelGameplayController.render`, and `LevelGameplayController` is actually a presenter.

kinda weird since the main game loop happens in the `render` method

imo, we should have a separate LevelGameplayPresenter class that does all the rendering, and invoke it in a single call from the render method of the controller

**Comment by roylin2000** [comment]
> almost good to go!!
> 
> currently,
> 
> ```
> inputController.handleInputs(dt);
> levelManager.step(dt);
> ```
> 
> are invokeed in `LevelGameplayController.render`, and `LevelGameplayController` is actually a presenter.
> 
> kinda weird since the main game loop happens in the `render` method
> 
> imo, we should have a separate LevelGameplayPresenter class that does all the rendering, and invoke it in a single call from the render method of the controller

I agree, LevelGameplayController is a bit cluttered with all the rendering. I think I'm going to rename LevelGameplayController to LevelGameplayPresenter since it extends Screen and has to do rendering stuff. Then I'll make another class called LevelGameplayController to do things like spawning.

**Review by matrix-marker — CHANGES_REQUESTED** [review]
`LevelGameplayPresenter` currently holds all the managers for non-presentation-related stuff, I think this is solid but simply the contents of the gameplay controller and presenter should be mostly swapped

**Review by matrix-marker — APPROVED** [review]
reworked collaboratively

**Pull request merged**
